
LD=gcc

CFLAGS+= -Wall
CFLAGS+= -Wstrict-prototypes -Wmissing-prototypes
CFLAGS+= -Wmissing-declarations
CFLAGS+= -Wshadow -Wpointer-arith -Wcast-qual
CFLAGS+= -Wsign-compare
LDADD=	-lutil

CPPFLAGS+=-DHAVE_PTY_H -DHAVE_UTMP_H

.c.o:
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $< -o $@

sshdrill: sshdrill.o strlcpy.o
	$(LD) -o $@ sshdrill.o strlcpy.o $(LDFLAGS) $(LDADD)
