
LD=gcc

CFLAGS+= -Wall
CFLAGS+= -Wstrict-prototypes -Wmissing-prototypes
CFLAGS+= -Wmissing-declarations
CFLAGS+= -Wshadow -Wpointer-arith -Wcast-qual
CFLAGS+= -Wsign-compare
LDADD=	-lutil
PREFIX?=/usr/local

CPPFLAGS+=-DHAVE_UTMP_H -DHAVE_STRLCPY -DHAVE_UTIL_H

.c.o:
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $< -o $@

sshdrill: sshdrill.o strlcpy.o
	$(LD) -o $@ sshdrill.o strlcpy.o $(LDFLAGS) $(LDADD)

install: sshdrill
	install -d $(PREFIX)/bin
	install sshdrill $(PREFIX)/bin
